# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('ref', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today', to='phrases.Frase')),
            ],
        ),
    ]
