# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('libros', 'Libros'), ('audios', 'Audios'), ('ideos', 'Videos')], default='libros', max_length=140),
            preserve_default=False,
        ),
    ]
