# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('libros', 'Libros'), ('audios', 'Audios'), ('videos', 'Videos')], max_length=140),
        ),
    ]
