# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_physicalproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fileName',
            field=models.CharField(default='BRIEF.pdf', max_length=200),
            preserve_default=False,
        ),
    ]
